# This workflow configures the user-statistician with the
# dark-dimmed color theme, but otherwise uses all of
# the defaults. It is configured on a daily schedule at 3am.

name: User Statistician

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/dark-dimmed.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Generate User Stats Image
      uses: cicirello/user-statistician@d1918dd362c46c2dc1788139947224eee4fef0b8 # v1.24.2
      with:
        colors: dark-dimmed
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
